name:                haskell-reversi
version:             0.1.0.0
github:              "matsubara0507/haskell-reversi"
license:             BSD3
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/haskell-reversi#readme>

dependencies:
- base >= 4.7 && < 5
- matrix

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints


library:
  source-dirs: src

executables:
  reversi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-reversi

tests:
  reversi-tasty:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-reversi
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-smallcheck
